[package]
name = "advens-of-code"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["now"] }
clap = { version = "4.0", features = ["derive"] }
itertools = "0.13.0"
memoize = "0.4.2"
pathfinding = "4.12.0"
regex = "1.11.1"
